### ISSUE TITLE
Add zgenom

### ISSUE THREAD

**Issue by unixorn** [rossmacarthur/zsh-plugin-manager-benchmark#4]
[zgenom](https://github.com/jandamm/zgenom) is a fork of zgen that's still getting actively developed.

**Comment by rossmacarthur** [comment]
Added in 4f93e58b75709f739df907a60df34256188e41e8, will close issue when results are updated

**Comment by rossmacarthur** [comment]
Added in a9025f6ff3e1e8014e091a6a67af01b74ffbcf92, still need to update the results.
